apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-eawsamss
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-eawsamss:344619a0529e79130132a27527523a8f0bcac52f@sha256:aec7370e5ebe289e233de58d8f41083256f5d337ff5b61e308a74f01b6a94ec4
          name: container-image
